/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiTest: typeof import('./src/frontend/components/ApiTest.vue')['default']
    HelloWorld: typeof import('./src/frontend/components/HelloWorld.vue')['default']
    RdBaseActionCard: typeof import('./src/frontend/components/rd/Base/ActionCard/index.vue')['default']
    'RdBaseActionCardActionCard.story': typeof import('./src/frontend/components/rd/Base/ActionCard/ActionCard.story.vue')['default']
    RdBaseButton: typeof import('./src/frontend/components/rd/Base/Button/index.vue')['default']
    'RdBaseButtonButton.story': typeof import('./src/frontend/components/rd/Base/Button/Button.story.vue')['default']
    RdBaseFeatureCard: typeof import('./src/frontend/components/rd/Base/FeatureCard.vue')['default']
    'RdBaseFeatureCard.story': typeof import('./src/frontend/components/rd/Base/FeatureCard.story.vue')['default']
    RdBaseFeatureItem: typeof import('./src/frontend/components/rd/Base/FeatureItem/index.vue')['default']
    'RdBaseFeatureItemFeatureItem.story': typeof import('./src/frontend/components/rd/Base/FeatureItem/FeatureItem.story.vue')['default']
    RdBaseLink: typeof import('./src/frontend/components/rd/Base/Link.vue')['default']
    'RdBaseLink.story': typeof import('./src/frontend/components/rd/Base/Link.story.vue')['default']
    RdBaseSectionHeader: typeof import('./src/frontend/components/rd/Base/SectionHeader.vue')['default']
    'RdBaseSectionHeader.story': typeof import('./src/frontend/components/rd/Base/SectionHeader.story.vue')['default']
    RdHeadlineGradient: typeof import('./src/frontend/components/rd/HeadlineGradient/index.vue')['default']
    'RdHeadlineGradientHeadlineGradient.story': typeof import('./src/frontend/components/rd/HeadlineGradient/HeadlineGradient.story.vue')['default']
    RdLayoutHeader: typeof import('./src/frontend/components/rd/layout/Header.vue')['default']
    'RdLayoutHeader.story': typeof import('./src/frontend/components/rd/layout/Header.story.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAccordionAccordion: typeof import('./src/frontend/components/ui/accordion/Accordion.vue')['default']
    UiAccordionAccordionContent: typeof import('./src/frontend/components/ui/accordion/AccordionContent.vue')['default']
    UiAccordionAccordionItem: typeof import('./src/frontend/components/ui/accordion/AccordionItem.vue')['default']
    UiAccordionAccordionTrigger: typeof import('./src/frontend/components/ui/accordion/AccordionTrigger.vue')['default']
    UiAlertAlert: typeof import('./src/frontend/components/ui/alert/Alert.vue')['default']
    UiAlertAlertDescription: typeof import('./src/frontend/components/ui/alert/AlertDescription.vue')['default']
    UiAlertAlertTitle: typeof import('./src/frontend/components/ui/alert/AlertTitle.vue')['default']
    UiBadgeBadge: typeof import('./src/frontend/components/ui/badge/Badge.vue')['default']
    UiButtonButton: typeof import('./src/frontend/components/ui/button/Button.vue')['default']
    UiCardCard: typeof import('./src/frontend/components/ui/card/Card.vue')['default']
    UiCardCardContent: typeof import('./src/frontend/components/ui/card/CardContent.vue')['default']
    UiCardCardDescription: typeof import('./src/frontend/components/ui/card/CardDescription.vue')['default']
    UiCardCardFooter: typeof import('./src/frontend/components/ui/card/CardFooter.vue')['default']
    UiCardCardHeader: typeof import('./src/frontend/components/ui/card/CardHeader.vue')['default']
    UiCardCardTitle: typeof import('./src/frontend/components/ui/card/CardTitle.vue')['default']
    UiSeparatorSeparator: typeof import('./src/frontend/components/ui/separator/Separator.vue')['default']
    UiTooltipTooltip: typeof import('./src/frontend/components/ui/tooltip/Tooltip.vue')['default']
    UiTooltipTooltipContent: typeof import('./src/frontend/components/ui/tooltip/TooltipContent.vue')['default']
    UiTooltipTooltipProvider: typeof import('./src/frontend/components/ui/tooltip/TooltipProvider.vue')['default']
    UiTooltipTooltipTrigger: typeof import('./src/frontend/components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
