#!/usr/bin/env sh

# Run lint-staged
npx lint-staged
npm run format
npm run lint
npm run type-check
npm run type-check:vue
npm run i18n:audit
# Run a targeted test suite that only includes our repo tests (not node_modules)
npm run test:repo
