name: CI

on:
  push:
    branches: [ main ]
    # Don't run this workflow when a tag is pushed
    tags-ignore: [ 'v*' ]
  pull_request:
    # Run on all pull requests regardless of target branch
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Add PostgreSQL service container
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: openbadges
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run database migrations
        run: bun run db:migrate
        env:
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges
      - name: Run tests
        run: bun run test
        env:
          RD_GITHUB_CLIENT_ID: ${{ secrets.RD_GITHUB_CLIENT_ID }}
          RD_GITHUB_CLIENT_SECRET: ${{ secrets.RD_GITHUB_CLIENT_SECRET }}
          RD_JWT_SECRET: ${{ secrets.RD_JWT_SECRET }}
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges

  # Build job removed - builds only happen in the release workflow
  # See release.yml for build and deployment configuration

  # Removed deploy job - deployment will be handled by the release workflow
