name: CI

on:
  push:
    branches: [ main ]
    # Don't run this workflow when a tag is pushed
    tags-ignore: [ 'v*' ]
  pull_request:
    # Run on all pull requests regardless of target branch
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run tests
        run: bun run test
        env:
          RD_GITHUB_CLIENT_ID: ${{ secrets.RD_GITHUB_CLIENT_ID }}
          RD_GITHUB_CLIENT_SECRET: ${{ secrets.RD_GITHUB_CLIENT_SECRET }}
          RD_JWT_SECRET: ${{ secrets.RD_JWT_SECRET }}

  # Build job removed - builds only happen in the release workflow
  # See release.yml for build and deployment configuration

  # Removed deploy job - deployment will be handled by the release workflow
