name: Release

on:
  push:
    tags:
      - 'v*' # Run only when a tag is pushed with the format v*, e.g., v1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    # Add PostgreSQL service container
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: openbadges
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run database migrations
        run: bun run db:migrate
        env:
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges
      - name: Run tests
        run: bun test
        env:
          RD_GITHUB_CLIENT_ID: ${{ secrets.RD_GITHUB_CLIENT_ID }}
          RD_GITHUB_CLIENT_SECRET: ${{ secrets.RD_GITHUB_CLIENT_SECRET }}
          RD_JWT_SECRET: ${{ secrets.RD_JWT_SECRET }}
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges

  build:
    runs-on: ubuntu-latest
    needs: test
    # Add PostgreSQL service container
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: openbadges
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run database migrations
        run: bun run db:migrate
        env:
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges
      - name: Build
        run: bun run build
        env:
          RD_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/openbadges
          RD_JWT_SECRET: ${{ secrets.RD_JWT_SECRET }}
          RD_GITHUB_CLIENT_ID: ${{ secrets.RD_GITHUB_CLIENT_ID }}
          RD_GITHUB_CLIENT_SECRET: ${{ secrets.RD_GITHUB_CLIENT_SECRET }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/
            Dockerfile
            fly.toml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          # Pass environment variables needed for the application
          RD_DATABASE_URL: ${{ secrets.RD_DATABASE_URL }}
          RD_JWT_SECRET: ${{ secrets.RD_JWT_SECRET }}
          RD_GITHUB_CLIENT_ID: ${{ secrets.RD_GITHUB_CLIENT_ID }}
          RD_GITHUB_CLIENT_SECRET: ${{ secrets.RD_GITHUB_CLIENT_SECRET }}
